version: "3.8"

services:
  tf2:
    image: cm2network/tf2:sourcemod-x64 # 64-битная версия с SourceMod

    container_name: tf2-ze
    ports:
      - "27015:27015/udp" # Game port (обязательно UDP!)
      - "27015:27015/tcp" # RCON
      - "27020:27020/udp" # SourceTV (опционально)
      - "27005:27005/udp" # Client port (иногда нужен)

    stdin_open: true
    tty: true
    restart: unless-stopped
    volumes:
      - ./tf2-server:/home/steam/tf-dedicated
    environment:
      SRCDS_TOKEN: "{SRCDS_TOKEN}"
      SRCDS_RCONPW: "supersecket"
      SRCDS_PW: ""
      SRCDS_HOSTNAME: "TF2 Zombie Escape 64-bit | Docker"
      SRCDS_MAXPLAYERS: "24"
      SRCDS_STARTMAP: "pl_cashworks"
      SRCDS_TICKRATE: "66"
      SRCDS_FPSMAX: "300"
      SRCDS_PORT: "27015"
