services:
  tf2:
    image: cm2network/tf2:sourcemod # 64-битная версия с SourceMod
    container_name: tf2
    ports:
      - "27015:27015/udp" # Game port (обязательно UDP!)
      - "27015:27015/tcp" # RCON
      - "27020:27020/udp" # SourceTV (опционально)
      - "27005:27005/udp" # Client port (иногда нужен)

    stdin_open: true
    tty: true
    restart: unless-stopped
    volumes:
      - ./tf2-server:/home/steam/tf-dedicated
      - ./tf2-data/addons:/home/steam/tf-dedicated/tf/addons # Комментируем при первом запуске
      - ./tf2-data/cfg:/home/steam/tf-dedicated/tf/cfg # Комментируем при первом запуске
      - ./tf2-data/platform:/home/steam/tf-dedicated/platform # Комментируем при первом запуске
    environment:
      SRCDS_TOKEN: "{SRCDS_TOKEN}"
      SRCDS_RCONPW: "supersecket"
      SRCDS_PW: ""
      SRCDS_HOSTNAME: "TF2"
      SRCDS_MAXPLAYERS: "24"
      SRCDS_STARTMAP: "ctf_2fort"
      SRCDS_TICKRATE: "66"
      SRCDS_FPSMAX: "300"
      SRCDS_PORT: "27015"
